### ISSUE TITLE
broadpwn

### ISSUE THREAD

**Issue by mailinneberg** [ReversingSwitch/BroadPWN#1]
Do you have a way to take root access to iPhone 7 /6 by security hole of Broadpwin?
Please answer

**Comment by toiry921** [comment]
AFAIK Without KPP bypass it would be fairly useless in terms of jailbreak and the versions with KPP bypass have better jailbreaks so just use Yalu and even then it's fixed in more recent versions so it's not entirely useful

**Comment by mailinneberg** [comment]
Hello

**Comment by mailinneberg** [comment]
sorry, who are you?

**Comment by toiry921** [comment]
err the owner of this repo

**Comment by mailinneberg** [comment]
Sorry, thank you for answer and can ask you more questions?

**Comment by toiry921** [comment]
err yeah you can do it though my email

**Comment by mailinneberg** [comment]
Hello

Do you have a way to take root access to iPhone 7 /6 by security hole of
Broadpwin?

Will you help for developing world best forensic software?

About Broadpwn when we read architecture of method we thought is is very
difficult to get into the iOS kernel level.

Best,
Mail
