### ISSUE TITLE
Unable to get working on Kali Linux

### ISSUE THREAD

**Issue by Wr3tched** [ReversingSwitch/BroadPWN#2]
Hi! This may be my own stupidity, but your files don't exist... I mean, the code refers to files that don't exist. I'll just paste the output of my terminal for you. I'll let that do the talking for me:

root@kali:~# bash '/root/BroadPWN/startit.sh'
cp: cannot stat 'hostapd-hotspot-template.conf': No such file or directory
/root/BroadPWN/startit.sh: line 2: sploit.txt: No such file or directory
Configuration file: hostapd-hotspot.conf
Line 1: unknown configuration item 'assocresp_elements'
Line 3: unknown configuration item 'assocresp_elements'
Line 5: unknown configuration item 'assocresp_elements'
Line 6: invalid line '0000000000000000000000'
Line 7: Invalid vendor_elements 'ddff0050f2020101000003a4000027a4000042435e0062322f0000000000000000000000000000000000000000007800000000000000414141414141414141414141414141410000000041414141000000004141414141414141414141414141414141414141414141414141414100000000c870210041414141414141412de9ff4300f003f80fbc74f7f9ba044b044a1a60044a014b1360704788842400d08a1b0000207047c497230000000000280000000000000084b61800d07021005e071079c8702100000000000000000000000000000000000000000000000000240100000000000000000000000000000000000000000000000'
Line 8: invalid line '0000000000000000000'
Line 9: unknown configuration item 'assocresp_elements'
Line 10: invalid line '0000000000000000000000'
Line 11: Invalid vendor_elements 'ddff0050f2020101000003a4000027a4000042435e0062322f0000000000000000000000000000000000000000007800000000000000414141414141414141414141414141410000000041414141000000004141414141414141414141414141414141414141414141414141414100000000c870210041414141414141412de9ff4300f003f80fbc74f7f9ba044b044a1a60044a014b1360704788842400d08a1b0000207047c497230000000000280000000000000084b61800d07021005e071079c8702100000000000000000000000000000000000000000000000000240100000000000000000000000000000000000000000000000'
Line 12: invalid line '0000000000000000000'
Line 13: unknown configuration item 'assocresp_elements'
Line 14: invalid line '0000000000000000000000'
Line 15: Invalid vendor_elements 'ddff0050f2020101000003a4000027a4000042435e0062322f0000000000000000000000000000000000000000007800000000000000414141414141414141414141414141410000000041414141000000004141414141414141414141414141414141414141414141414141414100000000c870210041414141414141412de9ff4300f003f80fbc74f7f9ba044b044a1a60044a014b1360704788842400d08a1b0000207047c497230000000000280000000000000084b61800d07021005e071079c8702100000000000000000000000000000000000000000000000000240100000000000000000000000000000000000000000000000'
Line 16: invalid line '0000000000000000000'
Line 17: unknown configuration item 'assocresp_elements'
Line 18: invalid line '0000000000000000000000'
Line 19: Invalid vendor_elements 'ddff0050f2020101000003a4000027a4000042435e0062322f0000000000000000000000000000000000000000007800000000000000414141414141414141414141414141410000000041414141000000004141414141414141414141414141414141414141414141414141414100000000c870210041414141414141412de9ff4300f003f80fbc74f7f9ba044b044a1a60044a014b1360704788842400d08a1b0000207047c497230000000000280000000000000084b61800d07021005e071079c8702100000000000000000000000000000000000000000000000000240100000000000000000000000000000000000000000000000'
Line 20: invalid line '0000000000000000000'
Line 21: unknown configuration item 'assocresp_elements'
Line 22: invalid line '0000000000000000000000'
Line 23: Invalid vendor_elements 'ddff0050f2020101000003a4000027a4000042435e0062322f0000000000000000000000000000000000000000007800000000000000414141414141414141414141414141410000000041414141000000004141414141414141414141414141414141414141414141414141414100000000c870210041414141414141412de9ff4300f003f80fbc74f7f9ba044b044a1a60044a014b1360704788842400d08a1b0000207047c497230000000000280000000000000084b61800d07021005e071079c8702100000000000000000000000000000000000000000000000000240100000000000000000000000000000000000000000000000'
Line 24: invalid line '0000000000000000000'
Line 25: unknown configuration item 'assocresp_elements'
Line 26: invalid line '0000000000000000000000'
Line 27: Invalid vendor_elements 'ddff0050f2020101000003a4000027a4000042435e0062322f0000000000000000000000000000000000000000007800000000000000414141414141414141414141414141410000000041414141000000004141414141414141414141414141414141414141414141414141414100000000c870210041414141414141412de9ff4300f003f80fbc74f7f9ba044b044a1a60044a014b1360704788842400d08a1b0000207047c497230000000000280000000000000084b61800d07021005e071079c8702100000000000000000000000000000000000000000000000000240100000000000000000000000000000000000000000000000'
Line 28: invalid line '0000000000000000000'
Line 29: unknown configuration item 'assocresp_elements'
Line 30: invalid line '0000000000000000000000'
Line 31: Invalid vendor_elements 'ddff0050f2020101000003a4000027a4000042435e0062322f0000000000000000000000000000000000000000007800000000000000414141414141414141414141414141410000000041414141000000004141414141414141414141414141414141414141414141414141414100000000c870210041414141414141412de9ff4300f003f80fbc74f7f9ba044b044a1a60044a014b1360704788842400d08a1b0000207047c497230000000000280000000000000084b61800d07021005e071079c8702100000000000000000000000000000000000000000000000000240100000000000000000000000000000000000000000000000'
Line 32: invalid line '0000000000000000000'
Line 33: unknown configuration item 'assocresp_elements'
Line 34: invalid line '0000000000000000000000'
Line 35: Invalid vendor_elements 'ddff0050f2020101000003a4000027a4000042435e0062322f0000000000000000000000000000000000000000007800000000000000414141414141414141414141414141410000000041414141000000004141414141414141414141414141414141414141414141414141414100000000c870210041414141414141412de9ff4300f003f80fbc74f7f9ba044b044a1a60044a014b1360704788842400d08a1b0000207047c497230000000000280000000000000084b61800d07021005e071079c8702100000000000000000000000000000000000000000000000000240100000000000000000000000000000000000000000000000'
Line 36: invalid line '0000000000000000000'
Line 37: unknown configuration item 'assocresp_elements'
Line 39: unknown configuration item 'assocresp_elements'
Line 41: unknown configuration item 'assocresp_elements'
Line 43: unknown configuration item 'assocresp_elements'
Line 45: unknown configuration item 'assocresp_elements'
39 errors found in configuration file 'hostapd-hotspot.conf'
Failed to set up interface with hostapd-hotspot.conf
Failed to initialize interface

I don't know bash... What exactly am I doing wrong, here?

**Comment by toiry921** [comment]
try using sh instead of bash

**Comment by Wr3tched** [comment]
Same output.

**Comment by toiry921** [comment]
make sure you have hostapd installed, then check to verify that you have all the files that are listed in the repo and if not then re-download

**Comment by Wr3tched** [comment]
See, I believe the issue is the version. Do you know any way to "apt-get"
the newest version of hostapd? It seems that I can't get 2.6. It isn't in
the Kali repos.

On Oct 3, 2017 7:14 PM, "toiry921" <notifications@github.com> wrote:

make sure you have hostapd installed, then check to verify that you have
all the files that are listed in the repo and if not then re-download

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ReversingSwitch/BroadPWN/issues/2#issuecomment-334031671>,
or mute the thread

**Comment by toiry921** [comment]
if it isn't avaliable then build it from [source](https://w1.fi/hostapd/)

**Comment by Wr3tched** [comment]
Wot

**Comment by toiry921** [comment]
it isn't that hard to do and if you can't build it from source this tool won't be of much use to you

**Comment by Wr3tched** [comment]
Lmao got it. Thanks for helping my stupid a** (can I swear on github?!
😱😱😱)

**Comment by toiry921** [comment]
don't see why not

**Comment by Wr3tched** [comment]
Fuck yeah!

**Comment by Wr3tched** [comment]
Do you have any forms of social media? I still would like to talk about
some small issues. I apparently do have the latest version of hostapd. My
issue is all of these "invalid lines" and "unknown configuration items".
Also, hostapd finds errors in the config file... How do I even specify an
interface? What is this?!

**Comment by Wr3tched** [comment]
Alright. Done. I fixed most of the issues but I still have "Invalid
vendor_elements" and then line 6's "invalid line" proceeding a string of
zeros.

**Comment by v4l3nc3** [comment]
Yeah... You should help fix those. This really isnt closed

**Comment by toiry921** [comment]
Well for interface its based off of your wifi-card and you have to point the config of hostapd to it, as well as change the driver on the wifi-card. outside of that everything should be set to go as long as you have python installed and launch startit.sh. Sorry I don't know Kali Linux that well, but the issue sounds to be user side with an improper download using `git clone https://github.com/ReversingSwitch/BroadPWN` gives you everything that is required from the repo, outside of that without knowing the specifics of hardware there is nothing else I could do.

**Comment by Wr3tched** [comment]
So, what is my problem here. Just, please. For the love of god. Help.

Configuration file: /root/BroadPWN/hostapd-hotspot.conf
Line 5: Invalid vendor_elements 'ddff0050f2020101000003a4000027a4000042435e0062322f0000000000000000000000000000000000000000007800000000000000414141414141414141414141414141410000000041414141000000004141414141414141414141414141414141414141414141414141414100000000c870210041414141414141412de9ff4300f003f80fbc74f7f9ba044b044a1a60044a014b1360704788842400d08a1b0000207047c497230000000000280000000000000084b61800d07021005e071079c8702100000000000000000000000000000000000000000000000000240100000000000000000000000000000000000000000000000'
Line 6: invalid line '0000000000000000000'
2 errors found in configuration file '/root/BroadPWN/hostapd-hotspot.conf'
Failed to set up interface with /root/BroadPWN/hostapd-hotspot.conf
Failed to initialize interface

What the HELL. I've tried everything. I NEED to ask you again.
